
DATA_TABLE: "../../merge_trees/DataTable_pp.root"
SIGNAL_TABLE: "../../merge_trees/SignalTable_pp_MC_mtexp.root"
BKG_TABLE: "../../merge_trees/DataTable_pp_LS.root"

TRAINING: True
BACKGROUND_OVER_SIGNAL: 4
OPTIMIZE: False
APPLICATION: True 
SIGNIFICANCE_SCAN: True
EFF_WORKING_POINT: 0.72
SYST_VARIATION_RANGE: 0.05


XGBOOST_PARAMS:
  # general parameters
  n_jobs: 30 # number of available threads
  # learning task parameters
  objective: binary:logistic
  random_state: 42
  eval_metric: auc
  tree_method: hist


HYPERPARAMS:
  # max_depth: 13
  # learning_rate: 0.0982
  # n_estimators: 181
  # gamma: 0.4467
  # min_child_weight: 5.75
  # subsample: 0.74
  # colsample_bytree: 0.57
  seed: 42
