
DATA_TABLE: "DataTable_pPb.root"
SIGNAL_TABLE: "SignalTable_17d_mtexp.root"
BKG_TABLE: "DataTable_pPb_LS.root"

TRAINING: False
BACKGROUND_OVER_SIGNAL: 4
OPTIMIZE: False
APPLICATION: True 
SIGNIFICANCE_SCAN: True
EFF_WORKING_POINT: 0.72
SYST_VARIATION_RANGE: 0.05


XGBOOST_PARAMS:
  # general parameters
  silent: 1 # print message (useful to understand whats happening)
  n_jobs: 8 # number of available threads
  # learning task parameters
  objective: binary:logistic
  random_state: 42
  eval_metric: auc
  tree_method: hist


HYPERPARAMS:
  # max_depth: 13
  # learning_rate: 0.0982
  # n_estimators: 181
  # gamma: 0.4467
  # min_child_weight: 5.75
  # subsample: 0.74
  # colsample_bytree: 0.57
  seed: 42